#!/usr/bin/env python3
"""weekly_expand.py — emit the next five-composer batch brief for Cursor agents.

Reads proposals/composer-queue.json. Does not edit the seed and does not invent
assessments. Humans confirm the batch; Role A agents implement the seed PR.
"""

from __future__ import annotations

import argparse
import json
import pathlib
from datetime import date

ROOT = pathlib.Path(__file__).resolve().parents[1]
QUEUE = ROOT / "proposals" / "composer-queue.json"
BRIEF = ROOT / "proposals" / "WEEK_BRIEF.md"


def load_queue() -> dict:
    return json.loads(QUEUE.read_text("utf-8"))


def next_batch(doc: dict, n: int | None = None) -> list[dict]:
    size = n or int(doc.get("batch_size", 5))
    batch = [c for c in doc["queue"] if c.get("status") == "next"]
    if len(batch) < size:
        for c in doc["queue"]:
            if c.get("status") == "queued" and c not in batch:
                batch.append(c)
            if len(batch) >= size:
                break
    return batch[:size]


def render_brief(doc: dict, batch: list[dict], week: str) -> str:
    lines = [
        f"# Week brief — {week}",
        "",
        "Generated by `agents/weekly_expand.py`. Binding rules: `AGENTS.md`.",
        "Orchestration: `docs/automation/README.md`.",
        "",
        "## Batch (five composers)",
        "",
    ]
    for c in batch:
        hints = c.get("core_works_hint") or ["(Role A: propose ~10–12 core works from standard repertory facts)"]
        lines.append(f"### {c['name']} (`{c['id']}`, {c['dates']})")
        lines.append("")
        for h in hints:
            lines.append(f"- {h}")
        lines.append("")

    lines += [
        "## Role A — Seed expander",
        "",
        "Branch: `cursor/seed-week-" + week.replace("-", "") + "-5458`",
        "",
        "1. Add each composer to `engine/seed_catalogue.py` with ~10–12 works and "
        "well-known candidate recordings (performers, label, year — facts only).",
        "2. Run `make seed`. Update `TestSeedIntegrity` expected counts.",
        "3. Update nav/copy in `site/build_site.py` for the new composer count.",
        "4. `make test && python3 agents/validate.py && make site`.",
        "5. Open a PR. Mark these five as `status: in_progress` in "
        "`proposals/composer-queue.json` with `week: " + week + "`.",
        "",
        "**Forbidden:** scores, stars, statements, review text, cover binaries.",
        "",
        "## Role B — Identity & covers",
        "",
        "After Role A merges (or on the same PR only if identity is separate):",
        "`make plan` then `make harvest CONTACT=…` with budget 300. "
        "Proposals only. CAA hotlinks only.",
        "",
        "## Role C — Citations toward ≥5 sources",
        "",
        "Emit award/citation proposals for assessed backlog first, then new works. "
        "Target sources listed in `docs/automation/AGENT_ROLES.md`. "
        "No publication scraping; check terms + robots before any fetch.",
        "",
        "## Role D — Composer rollup",
        "",
        "Confirm `make score` writes `composers[]` rollups; show on index only "
        "when non-null. Do not alter the four regression recording scores.",
        "",
        "## Human gates",
        "",
        "- Confirm identity matches (no compilations / wrong decade).",
        "- Ratify every statement before it enters `data/statements/`.",
        "- ADR-003 quotes only inside Critic-signed editorial entries.",
        "- Signed editorial is Critic’s path (`docs/automation/CRITIC.md`): "
        "land on main / Pages; no human merge babysit. Developer may ship.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--week", default=date.today().isoformat(),
                    help="ISO week label stored in the brief (default: today)")
    ap.add_argument("--write", action="store_true",
                    help=f"write {BRIEF.relative_to(ROOT)}")
    ap.add_argument("--json", action="store_true",
                    help="print the batch as JSON")
    args = ap.parse_args()

    doc = load_queue()
    batch = next_batch(doc)
    if args.json:
        print(json.dumps(batch, indent=2, ensure_ascii=False))
        return

    brief = render_brief(doc, batch, args.week)
    print(brief)
    if args.write:
        BRIEF.write_text(brief, "utf-8")
        print(f"\nWrote {BRIEF.relative_to(ROOT)}", flush=True)


if __name__ == "__main__":
    main()
